import { createGroq } from "@ai-sdk/groq";
import { generateText } from "ai";
import { NextRequest, NextResponse } from "next/server";

const groq = createGroq({ apiKey: process.env.GROQ_API_KEY });

export const runtime = "nodejs";
export const maxDuration = 60;

// ─── Model configuration ────────────────────────────────────────────────────
// Llama 4 Maverick for detection — strong reasoning, large context
// Llama 3.3 70B for humanization — best for creative rewriting
const DETECT_MODEL = "meta-llama/llama-4-maverick-17b-128e-instruct";
const HUMANIZE_MODEL = "llama-3.3-70b-versatile";

// ─── AI Detection (improved prompt with sentence-level analysis) ─────────────

const DETECT_SYSTEM = `You are an advanced AI content analysis engine. Your job is to determine whether a given text was written by a human, generated by an AI (GPT-4, Claude, Gemini, LLaMA, etc.), or a mix.

ANALYSIS METHODOLOGY — follow each step:

1. **Sentence-level scan**: Check every sentence individually. Flag sentences that show classic AI patterns:
   - Formulaic transitions: "Moreover", "Furthermore", "In conclusion", "It is worth noting", "Let's delve into"
   - Hedging/filler: "It is important to note", "plays a crucial role", "a wide range of", "various factors"
   - Uniform structure: sentences of roughly equal length, consistently 15-25 words
   - Robotic parallelism: "Not only... but also...", repeated sentence templates

2. **Paragraph uniformity**: AI outputs tend to have paragraphs of almost identical word counts. Human text varies wildly.

3. **Voice & personality**: Check for contractions (don't, can't, it's), first-person pronouns (I, we, my), colloquial language, humor, rhetorical questions, exclamations, personal anecdotes. Their absence strongly suggests AI.

4. **Vocabulary richness**: Count unique-to-total word ratio. AI tends to reuse the same "safe" vocabulary. Humans use slang, domain jargon, and unexpected word choices.

5. **Error patterns**: Typos, minor grammar lapses, inconsistent formatting — these indicate human authorship. AI is typically error-free with perfect punctuation.

Return ONLY a valid JSON object — no explanation, no markdown, no code fences:

{
  "score": <integer 0-100, 0=definitely human, 100=definitely AI>,
  "label": <"Human" | "Likely Human" | "Mixed" | "Likely AI" | "AI Generated">,
  "confidence": <"Low" | "Medium" | "High">,
  "indicators": [<up to 6 specific, evidence-based indicators from your analysis>],
  "flaggedSentences": <number of sentences that show AI patterns>,
  "totalSentences": <total number of sentences analyzed>,
  "summary": <2-3 sentence explanation with specific examples from the text>
}

Scoring guide:
- 0-20: Clearly human — personal voice, typos, emotional, casual, inconsistent formatting
- 21-40: Likely human — some structure but personal tone, contractions, personality
- 41-59: Mixed — could be AI-edited by a human or structured human writing
- 60-79: Likely AI — formulaic structure, consistent tone, transition patterns
- 80-100: Clearly AI — near-perfect uniformity, hedging, zero personality, generic examples`;

// ─── Humanize (improved with style options) ──────────────────────────────────

const HUMANIZE_SYSTEM = `You are a professional writer and editor who specializes in making AI-generated text sound indistinguishable from expert human writing. Rewrite the given text completely.

MANDATORY REWRITING RULES:

1. **Sentence length variety**: Mix very short sentences (3-6 words) with longer complex ones (25+ words). Never write three sentences of similar length in a row.

2. **Kill AI transitions**: Remove or replace every instance of: "Moreover", "Furthermore", "In conclusion", "It is worth noting", "It's important to note", "delve into", "dive into", "plays a crucial role", "a wide range of". Use natural alternatives or just start the next thought directly.

3. **Add personality**:
   - Use contractions (don't, can't, it's, we'll) — humans always do
   - Add occasional rhetorical questions
   - Use first-person naturally when appropriate ("I've found that..." or "In my experience...")
   - Vary paragraph sizes significantly — one paragraph can be 1 sentence, the next can be 5

4. **Vocabulary**: Replace generic/safe words with more specific ones. "utilize" → "use". "implement" → "build". "leverage" → just say what it does. Avoid corporate buzzwords.

5. **Natural imperfections**: Humans don't write perfectly structured essays. Use dashes — like this — for asides. Start sentences with "And" or "But" occasionally. Use sentence fragments for emphasis. Like this.

6. **Preserve all facts**: Every piece of information, technical term, code block, and proper noun must remain exactly as-is. Only change the STYLE, never the substance.

Return ONLY the rewritten text — no preamble, no "Here is the rewritten version:", no explanation.`;

export async function POST(req: NextRequest) {
  try {
    const { action, content, format } = await req.json();

    if (!content || typeof content !== "string") {
      return NextResponse.json({ success: false, error: "content is required" }, { status: 400 });
    }

    if (!action || !["detect", "humanize"].includes(action)) {
      return NextResponse.json({ success: false, error: "action must be 'detect' or 'humanize'" }, { status: 400 });
    }

    // Increased context window for better accuracy
    const maxChars = action === "detect" ? 15000 : 10000;
    const truncated = content.length > maxChars;
    const workingContent = content.slice(0, maxChars);

    if (action === "detect") {
      const { text } = await generateText({
        model: groq(DETECT_MODEL),
        system: DETECT_SYSTEM,
        messages: [
          {
            role: "user",
            content: `Analyze this ${format ?? "text"} content (${workingContent.split(/\s+/).length} words, ${workingContent.split(/\n\s*\n/).length} paragraphs):\n\n${workingContent}`,
          },
        ],
        maxOutputTokens: 1024,
        temperature: 0.1,
      });

      // Parse JSON from response
      let result;
      try {
        const jsonMatch = text.replace(/<think>[\s\S]*?<\/think>/g, "").match(/\{[\s\S]*\}/);
        result = JSON.parse(jsonMatch ? jsonMatch[0] : text);
      } catch {
        return NextResponse.json({ success: false, error: "Failed to parse AI response" }, { status: 500 });
      }

      return NextResponse.json({ success: true, ...result, truncated, model: DETECT_MODEL });
    }

    if (action === "humanize") {
      const { text } = await generateText({
        model: groq(HUMANIZE_MODEL),
        system: HUMANIZE_SYSTEM,
        messages: [
          {
            role: "user",
            content: `Rewrite this ${format ?? "text"} content to sound completely human-written:\n\n${workingContent}`,
          },
        ],
        maxOutputTokens: 8000,
        temperature: 0.8,
      });

      return NextResponse.json({ success: true, humanized: text, truncated, model: HUMANIZE_MODEL });
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
